sudo: required
language: node_js
services:
  - docker

before_install:
  - npm i -g npm@6.9.0
  - docker build -t troy/docker_react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true troy/docker_react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-475987840838"
  bucker_path: "docker-react"
  on:
    branch: master