sudo: required
language: node_js
services:
  - docker

before_install:
  - npm i -g npm@5.6.0
  - docker build -t troy/docker_react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true troy/docker_react npm run test

deploy:
  provider: elasticbeanstalk