sudo: required
language: node_js
services:
  - docker

before_install:
  - nvm install 8.11.4
  - nvm use 8.11.4
  - docker build -t troy/docker_react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true troy/docker_react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-475987840838"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY  
  secret_access_key:
    secret: $AWS_SECRET_ACCESS_KEY