sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t troy/docker_react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true troy/docker_react npm run test 