sudo: required
language: node_js
services:
  - docker

before_install:
  - nvm install 8.11.4
  - nvm use 8.11.4
  - docker build -t troy/docker_react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true troy/docker_react npm run test